//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/player_main_control.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_main_control : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_main_control()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""player_main_control"",
    ""maps"": [
        {
            ""name"": ""primary"",
            ""id"": ""8177715e-705d-4f50-a5fd-ab2e32ed3aa1"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""14c4f3ab-010d-4266-b826-c9cafd75d0c4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Value"",
                    ""id"": ""8d78fd4d-494b-404d-8a17-6f2a68f71098"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action1"",
                    ""type"": ""Button"",
                    ""id"": ""7f04468f-31e5-489b-9d37-9557651cb7ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""fe535c48-381c-4958-a3de-5404fb5fb7ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""interact"",
                    ""type"": ""Button"",
                    ""id"": ""cf5442b4-58b5-4553-8029-3b4d59a1be45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""reload"",
                    ""type"": ""Button"",
                    ""id"": ""bb5b9c82-de67-42d5-88be-d3d94cfdb88d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action2"",
                    ""type"": ""Button"",
                    ""id"": ""651859aa-8cb4-407b-b75d-bfb0a398a237"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action3"",
                    ""type"": ""Button"",
                    ""id"": ""884f2368-11e9-4fd0-b0c8-2edb02e8e198"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action4"",
                    ""type"": ""Button"",
                    ""id"": ""f38072de-a1ad-4b67-8f08-3afa8ba0c9aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action5"",
                    ""type"": ""Button"",
                    ""id"": ""e031c1d1-e7eb-4838-93a4-2b46bacb02c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""menu_pause"",
                    ""type"": ""Button"",
                    ""id"": ""1e9cf409-db37-4d4b-a351-263a54b152fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move_walk"",
                    ""type"": ""Button"",
                    ""id"": ""72932c46-69d3-4a98-a8d9-2265adbf336b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move_dash"",
                    ""type"": ""Button"",
                    ""id"": ""e4bf63c7-33e2-4971-8e47-40a2e7f56001"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5791917a-e5c8-4d2d-878b-e47f227327db"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""Action2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d13d602-eca0-481e-b047-d60b8de3b345"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""Action2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42af5b0c-8cf1-4839-8da1-c240770740c9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""Action3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5d8a7f9-285b-43af-a0b2-b23491d5be23"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""Action3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a04e929-c960-47dc-848d-eb1dc1fe6ef2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""Action4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4f79679-ca75-45b4-926e-7fb63a525eb1"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""Action4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81b180a7-b0a0-476b-b1c5-d4f9f164bc51"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""Action5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7526776a-712d-46a4-ab7a-7136ba52fc76"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""Action5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddb0e3a7-3a35-4ed1-9070-5c3ffb90d4a5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""menu_pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34641177-3f23-4bca-b4e2-7767d050ca92"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""menu_pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""457b948b-ccc6-4897-a47f-c06e5b4eca37"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""move_walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""573474ea-cb25-48b6-9bad-eba109a38bc1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""move_dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1b26728-450d-49fb-8a5f-c4dab2ed377c"",
                    ""path"": ""<XInputController>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""move_dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a184af82-8aa9-42ec-990c-0ec93e9a7718"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e7f73f3-e6e4-44e9-8fd7-1fe8537e45c6"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e35bf1f-ed1a-4958-beb8-669eca34052e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19e8852f-fe39-458f-abde-af3934152854"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1462aa04-a1bc-44c9-bd74-cad4f3b3fa0f"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""Action1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96ec7651-82fb-46b5-8ca3-db596fb77d4b"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""Action1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ff346bb-4be6-4557-89c6-7edba08fcd0a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec4deb35-939a-43af-a8b5-a57edc36e161"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""896731d6-8959-4fbc-aa3e-a7d6c4a7dc5e"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard_mouse"",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b5cb28c-ed13-4f6d-8950-fb5e96161e66"",
                    ""path"": ""<XInputController>/dpad/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XBOX_controller"",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""21b1d945-f352-41d0-966b-b39f3e8f78fb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5d01ad8b-f4cb-4c32-a703-d894289e649d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fd1d0985-4781-4025-9cc1-4547f3be3ed6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""419bff4e-c92b-40f5-9623-6b2727302b19"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b2612509-7866-4118-9db9-9b0eca44bbab"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6af46117-8d8d-483a-b1d2-3accf447707a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""keyboard_mouse"",
            ""bindingGroup"": ""keyboard_mouse"",
            ""devices"": []
        },
        {
            ""name"": ""XBOX_controller"",
            ""bindingGroup"": ""XBOX_controller"",
            ""devices"": []
        }
    ]
}");
        // primary
        m_primary = asset.FindActionMap("primary", throwIfNotFound: true);
        m_primary_move = m_primary.FindAction("move", throwIfNotFound: true);
        m_primary_Inventory = m_primary.FindAction("Inventory", throwIfNotFound: true);
        m_primary_Action1 = m_primary.FindAction("Action1", throwIfNotFound: true);
        m_primary_jump = m_primary.FindAction("jump", throwIfNotFound: true);
        m_primary_interact = m_primary.FindAction("interact", throwIfNotFound: true);
        m_primary_reload = m_primary.FindAction("reload", throwIfNotFound: true);
        m_primary_Action2 = m_primary.FindAction("Action2", throwIfNotFound: true);
        m_primary_Action3 = m_primary.FindAction("Action3", throwIfNotFound: true);
        m_primary_Action4 = m_primary.FindAction("Action4", throwIfNotFound: true);
        m_primary_Action5 = m_primary.FindAction("Action5", throwIfNotFound: true);
        m_primary_menu_pause = m_primary.FindAction("menu_pause", throwIfNotFound: true);
        m_primary_move_walk = m_primary.FindAction("move_walk", throwIfNotFound: true);
        m_primary_move_dash = m_primary.FindAction("move_dash", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // primary
    private readonly InputActionMap m_primary;
    private IPrimaryActions m_PrimaryActionsCallbackInterface;
    private readonly InputAction m_primary_move;
    private readonly InputAction m_primary_Inventory;
    private readonly InputAction m_primary_Action1;
    private readonly InputAction m_primary_jump;
    private readonly InputAction m_primary_interact;
    private readonly InputAction m_primary_reload;
    private readonly InputAction m_primary_Action2;
    private readonly InputAction m_primary_Action3;
    private readonly InputAction m_primary_Action4;
    private readonly InputAction m_primary_Action5;
    private readonly InputAction m_primary_menu_pause;
    private readonly InputAction m_primary_move_walk;
    private readonly InputAction m_primary_move_dash;
    public struct PrimaryActions
    {
        private @Player_main_control m_Wrapper;
        public PrimaryActions(@Player_main_control wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_primary_move;
        public InputAction @Inventory => m_Wrapper.m_primary_Inventory;
        public InputAction @Action1 => m_Wrapper.m_primary_Action1;
        public InputAction @jump => m_Wrapper.m_primary_jump;
        public InputAction @interact => m_Wrapper.m_primary_interact;
        public InputAction @reload => m_Wrapper.m_primary_reload;
        public InputAction @Action2 => m_Wrapper.m_primary_Action2;
        public InputAction @Action3 => m_Wrapper.m_primary_Action3;
        public InputAction @Action4 => m_Wrapper.m_primary_Action4;
        public InputAction @Action5 => m_Wrapper.m_primary_Action5;
        public InputAction @menu_pause => m_Wrapper.m_primary_menu_pause;
        public InputAction @move_walk => m_Wrapper.m_primary_move_walk;
        public InputAction @move_dash => m_Wrapper.m_primary_move_dash;
        public InputActionMap Get() { return m_Wrapper.m_primary; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PrimaryActions set) { return set.Get(); }
        public void SetCallbacks(IPrimaryActions instance)
        {
            if (m_Wrapper.m_PrimaryActionsCallbackInterface != null)
            {
                @move.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove;
                @Inventory.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnInventory;
                @Action1.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction1;
                @Action1.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction1;
                @Action1.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction1;
                @jump.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnJump;
                @jump.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnJump;
                @jump.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnJump;
                @interact.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnInteract;
                @interact.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnInteract;
                @interact.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnInteract;
                @reload.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnReload;
                @reload.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnReload;
                @reload.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnReload;
                @Action2.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction2;
                @Action2.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction2;
                @Action2.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction2;
                @Action3.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction3;
                @Action3.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction3;
                @Action3.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction3;
                @Action4.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction4;
                @Action4.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction4;
                @Action4.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction4;
                @Action5.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction5;
                @Action5.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction5;
                @Action5.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnAction5;
                @menu_pause.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMenu_pause;
                @menu_pause.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMenu_pause;
                @menu_pause.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMenu_pause;
                @move_walk.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove_walk;
                @move_walk.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove_walk;
                @move_walk.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove_walk;
                @move_dash.started -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove_dash;
                @move_dash.performed -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove_dash;
                @move_dash.canceled -= m_Wrapper.m_PrimaryActionsCallbackInterface.OnMove_dash;
            }
            m_Wrapper.m_PrimaryActionsCallbackInterface = instance;
            if (instance != null)
            {
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @Action1.started += instance.OnAction1;
                @Action1.performed += instance.OnAction1;
                @Action1.canceled += instance.OnAction1;
                @jump.started += instance.OnJump;
                @jump.performed += instance.OnJump;
                @jump.canceled += instance.OnJump;
                @interact.started += instance.OnInteract;
                @interact.performed += instance.OnInteract;
                @interact.canceled += instance.OnInteract;
                @reload.started += instance.OnReload;
                @reload.performed += instance.OnReload;
                @reload.canceled += instance.OnReload;
                @Action2.started += instance.OnAction2;
                @Action2.performed += instance.OnAction2;
                @Action2.canceled += instance.OnAction2;
                @Action3.started += instance.OnAction3;
                @Action3.performed += instance.OnAction3;
                @Action3.canceled += instance.OnAction3;
                @Action4.started += instance.OnAction4;
                @Action4.performed += instance.OnAction4;
                @Action4.canceled += instance.OnAction4;
                @Action5.started += instance.OnAction5;
                @Action5.performed += instance.OnAction5;
                @Action5.canceled += instance.OnAction5;
                @menu_pause.started += instance.OnMenu_pause;
                @menu_pause.performed += instance.OnMenu_pause;
                @menu_pause.canceled += instance.OnMenu_pause;
                @move_walk.started += instance.OnMove_walk;
                @move_walk.performed += instance.OnMove_walk;
                @move_walk.canceled += instance.OnMove_walk;
                @move_dash.started += instance.OnMove_dash;
                @move_dash.performed += instance.OnMove_dash;
                @move_dash.canceled += instance.OnMove_dash;
            }
        }
    }
    public PrimaryActions @primary => new PrimaryActions(this);
    private int m_keyboard_mouseSchemeIndex = -1;
    public InputControlScheme keyboard_mouseScheme
    {
        get
        {
            if (m_keyboard_mouseSchemeIndex == -1) m_keyboard_mouseSchemeIndex = asset.FindControlSchemeIndex("keyboard_mouse");
            return asset.controlSchemes[m_keyboard_mouseSchemeIndex];
        }
    }
    private int m_XBOX_controllerSchemeIndex = -1;
    public InputControlScheme XBOX_controllerScheme
    {
        get
        {
            if (m_XBOX_controllerSchemeIndex == -1) m_XBOX_controllerSchemeIndex = asset.FindControlSchemeIndex("XBOX_controller");
            return asset.controlSchemes[m_XBOX_controllerSchemeIndex];
        }
    }
    public interface IPrimaryActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnAction1(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnAction2(InputAction.CallbackContext context);
        void OnAction3(InputAction.CallbackContext context);
        void OnAction4(InputAction.CallbackContext context);
        void OnAction5(InputAction.CallbackContext context);
        void OnMenu_pause(InputAction.CallbackContext context);
        void OnMove_walk(InputAction.CallbackContext context);
        void OnMove_dash(InputAction.CallbackContext context);
    }
}
